In [41]:
# Import libraties and csv file
import pandas as pd

train_ds= pd.read_csv('csv_files/loan_train.csv')
train_ds.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [42]:
# Running standard inspections.

# Looking at the summary of dataset
train_ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [43]:
# Looking at summary statistics.
train_ds.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [44]:
# Checking data types
train_ds.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [45]:
# Checking for null vaules
train_ds.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

##### The column `Gender`, `Married`, `Dependents`, `Self_Employed`, `LoanAmount`, `Loan_Amount_Term` and `Credit_History` has missing values.

To fill these missing values, we need to apply two different methods.

- Fill the numerical columns with the median (the middle value) - `LoanAmount`, `Loan_Amount_Term`.
- Fill the categorical columns with mode (most frequent value) - `Gender`, `Married`, `Dependents`,  `Self_Employed`

In [46]:
# Filling missing numerical values with median

#Loan amount
loan_amt_mid =train_ds['LoanAmount'].median()
train_ds['LoanAmount'] = train_ds["LoanAmount"].fillna(loan_amt_mid)


# Loan_Amount_Term
loan_amt_term_mid =train_ds['Loan_Amount_Term'].median()
train_ds['Loan_Amount_Term'] = train_ds["Loan_Amount_Term"].fillna(loan_amt_term_mid)

# Credit History
credit_history_mid = train_ds['Credit_History'].median()
train_ds['Credit_History'] = train_ds['Credit_History'].fillna(credit_history_mid)

In [47]:
# Filling categorical columns with mode

# Gender
gender_md = train_ds['Gender'].mode()[0]
train_ds['Gender'] = train_ds['Gender'].fillna(gender_md)

# Married
married_md = train_ds['Married'].mode()[0]
train_ds['Married'] = train_ds['Married'].fillna(married_md)

#Dependents
dependents_md = train_ds['Dependents'].mode()[0]
train_ds['Dependents'] = train_ds['Dependents'].fillna(dependents_md)

# Self_employed
self_employed_md = train_ds['Self_Employed'].mode()[0]
train_ds['Self_Employed'] = train_ds['Self_Employed'].fillna(self_employed_md)

In [48]:
train_ds.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64